services:
  web:
    build: ./apps
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./apps/:./apps
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres

    postgres:
    container_name: pg
    image: postgres:17.2
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "debian"
      POSTGRES_PASSWORD: "Debian12"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U debian -d test_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
volumes:
  data:
